-- Add more comprehensive medical categories
INSERT INTO public.job_categories (name, description, is_medical, requires_subscription) VALUES
('Family Medicine', 'Family doctors and primary care physicians', true, true),
('Internal Medicine', 'Internal medicine specialists', true, false),
('Emergency Medicine', 'Emergency room doctors', true, false),
('Anesthesiology', 'Anesthesia specialists', true, false),
('Radiology', 'Medical imaging specialists', true, false),
('Pathology', 'Laboratory medicine specialists', true, false),
('Surgery - General', 'General surgery specialists', true, false),
('Surgery - Plastic', 'Plastic and reconstructive surgery', true, false),
('Surgery - Cardiac', 'Heart surgery specialists', true, false),
('Surgery - Neurosurgery', 'Brain and nervous system surgery', true, false),
('Oncology', 'Cancer treatment specialists', true, false),
('Endocrinology', 'Hormone and diabetes specialists', true, false),
('Gastroenterology', 'Digestive system specialists', true, false),
('Pulmonology', 'Lung and respiratory specialists', true, false),
('Rheumatology', 'Joint and autoimmune disease specialists', true, false),
('Infectious Disease', 'Infection and disease specialists', true, false),
('Geriatrics', 'Elderly care specialists', true, false),
('Sports Medicine', 'Sports injury and performance specialists', true, false),
('Physical Medicine', 'Rehabilitation and physical therapy doctors', true, false),
('Dentistry - General', 'General dental care', true, true),
('Dentistry - Orthodontics', 'Teeth alignment and braces specialists', true, false),
('Dentistry - Oral Surgery', 'Oral and maxillofacial surgery', true, false),
('Dentistry - Periodontics', 'Gum disease specialists', true, false),
('Psychology', 'Mental health counselors and psychologists', true, false),
('Pharmacy', 'Pharmacists and medication specialists', true, false),
('Nutrition', 'Dietitians and nutrition specialists', true, false),
('Physiotherapy', 'Physical therapy specialists', true, false),
('Nursing', 'Registered nurses and nursing specialists', true, false);