// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://svcklgpspnvjvdouqmvx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN2Y2tsZ3BzcG52anZkb3VxbXZ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyNTQyMTUsImV4cCI6MjA3MDgzMDIxNX0.9nvRrdRgy0FKSEU-FhJ8DdSHjyttQTHD5loYrtE3vRs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});